version: '3'

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    ports:
      - "8081:15672"
      - "5672:5672"
      - "25676:25676"

volumes:
  portainer_data:
